version: '3'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    volumes:
      - /Users/luevard/tpCICD/gitlab:/var/opt/gitlab/postgresql/data
    ports:
      - "8088:80"

#  dbRedmine:
#    image: postgres:latest
#    restart: always
#    volumes:
#      - /Users/luevard/tpCICD/postgresRedmine:/var/lib/postgresql/data
#    environment:
#      POSTGRES_PASSWORD: example
#      POSTGRES_USER: redmine

#  redmine:
#    image: redmine
#    ports:
#      - 8089:3000
#    environment:
#      REDMINE_DB_POSTGRES: dbRedmine
#      REDMINE_DB_USERNAME: redmine
#      REDMINE_DB_PASSWORD: example
#    depends_on: 
#     - dbRedmine

  GLPI:
    container_name: glpi
    image: emadruida/glpi
    ports:
      - "8090:80"
  
  dbGLPI:
    image: mysql
    container_name: dbGLPI
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mysupersecurepassword
      - MYSQL_DATABASE=glpi

  drone:
    image: drone/drone
    environment:
      - DRONE_GITLAB_SERVER=gitlab
      - DRONE_RPC_PROTO=https
      - DRONE_RPC_SECRET=secretdocker
      - DRONE_SERVER_HOST=drone.tphexa.com
      - DRONE_GITLAB_CLIENT_ID=f9865a91d27897dfab2e8c72cfbb5f1304c23008a90a44285b1306b486b4c374
      - DRONE_GITLAB_CLIENT_SECRET=gloas-58779076540261515606270f7a7cf0e466522061a25fb01675d87fd3dc757195

  runner:
    image: drone/drone-runner-docker:1
    environment:
      - DRONE_RPC_PROTO=https 
      - DRONE_RPC_HOST=drone.tphexa.com
      - DRONE_RPC_SECRET=super-duper-secret 
      - DRONE_RUNNER_CAPACITY=2 
      - DRONE_RUNNER_NAME=my-first-runner 
